# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44df08b4b6e5b9b5a40beefd5945abdb4b7207a55fb2ce7194cdc783d6c583e494b57acccca6751216b4473b10dc5ff77dfc9693c6568ac064d9ac3ed3b374c7

test:
  secret_key_base: ea4fe60da0f5de04ac4a0415e22c6f29553f66ea9f9a151300e8bac431b63217ad8cd847ea721ee7c994432c1d473a56281938a5a1b987ee7a064701a7c83917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
